services:
  - name: instagram-dm
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
